version: '3.3'

services:
  be_179927_presta:
    image: julekkrabel/be_179927
    ports:
      - 9928:80
      - 9927:443
    restart: always
    environment:
      PS_INSTALL_AUTO: 0
      PS_ERASE_DB: 0
      DB_HOST: actina15.maas
      DB_USER: be_179927
      DB_PASSWD: haslo
      DB_NAME: be_179927_db
      PS_DEV_MODE: 0
      ALLOW_OVERRIDE: 1
    deploy:
      replicas: 1
